Attempt to refresh expired music service tokens (fixes#890)
SoCo/SoCo pull request #893
Opened 2022-02-10 19:32 UTC by goldyfruit

This will try to find first the token and the key into the namespace
and fallback to `findtext()` if nothing has been found.

2022-02-10 19:42 UTC, jjlawren requested changes

2022-02-10 19:42 UTC, jjlawren commented on soco/music_services/music_service.py
>                  # If we didn't find the tokens, raise
This should be taken out.

2022-02-10 19:42 UTC, jjlawren commented on soco/music_services/music_service.py
> +                    if auth_token is None or private_key is None:
This should be moved out of the `if` block.

2022-02-10 19:42 UTC, jjlawren commented on soco/music_services/music_service.py
> +                    # </detail>
Leave this comment above where it was?

2022-02-10 19:59 UTC, goldyfruit commented on soco/music_services/music_service.py
> +                    # </detail>
True

2022-02-11 18:43 UTC, goldyfruit commented
@pwt have you been able to test this PR with your Spotify account to see if it fixes your token refresh issue?

2022-02-11 19:31 UTC, pwt commented
> @pwt have you been able to test this PR with your Spotify account to see if it fixes your token refresh issue?

Not yet. I'll give it a spin over the weekend. Thanks for working on this.

2022-02-16 13:41 UTC, jjlawren approved these changes
Looks good, I'd suggest removing one old comment.

2022-02-16 13:41 UTC, jjlawren commented on soco/music_services/music_service.py
> +                    if auth_token is None or private_key is None:
Actually this only needs to be raised if the backup attempt fails. Okay to keep where it is.

2022-02-16 13:41 UTC, jjlawren commented on soco/music_services/music_service.py
>                  # If we didn't find the tokens, raise
```suggestion
```

2022-02-16 14:54 UTC, pwt commented
Looks like this is good to merge. Thanks @goldyfruit and @jjlawren.
I'll include it in a patch release once I've reviewed/merged a few other changes.

2022-02-16 14:56 UTC, merged