Add support for subwoofer gain controls
SoCo/SoCo pull request #909
Opened 2022-03-08 23:10 UTC by jjlawren

Adds support for controlling the subwoofer gain using the `SoCo.sub_gain` property. This property name matches the key from the `RenderingControl` event payload.

Needs validation testing from a system that contains a subwoofer.

2022-03-09 01:07 UTC, bachya requested changes
Tested both the setter and getter and they look good: the Sonos app properly reflects the changes in both cases. Need to change the level limits.

2022-03-09 01:07 UTC, bachya commented on soco/core.py
> +        if not -10 <= level <= 10:
In my Sonos iOS app, the gain goes from -15 to 15.

2022-03-09 03:55 UTC, jjlawren commented
@bachya Thanks for testing, adjusted thresholds based on your feedback. 👍

2022-03-13 15:28 UTC, pwt commented
I'll test (and presumably merge) this later today. Sorry for the delay.

2022-03-13 18:27 UTC, pwt commented
Working perfectly with my Play:1 x 2 + Sub rig. Also behaving as expected when tested against a device without a Sub. 
Thanks for your work on this -- it's something I've (selfishly) wanted for a while.

I'll merge as-is, but it would be nice to add a test in a subsequent PR.

2022-03-13 18:28 UTC, merged