Add methods to get next alarm datetime
SoCo/SoCo pull request #951
Opened 2023-11-04 05:47 UTC by DaAwesomeP

I have added methods to more easily determine:
- The next `datetime` for an `Alarm`
- The next `datetime` for an `Alarms` (i.e. a whole zone/room)

These methods are particularly useful for home automation scenarios.

This is still a draft because I have not tested it yet.

Maybe there is a better name for the `bypass_disabled` argument?

2023-11-12 11:42 UTC, pwt commented
Thanks for the contribution.

> Maybe there is a better name for the bypass_disabled argument?

I'd be minded to invert this to be `include_disabled`, and to make the default `False`.

2023-11-12 13:56 UTC, pwt commented on soco/alarms.py
> +            from_datetime = datetime().now()
This should be `datetime.now()`

2023-11-12 13:57 UTC, pwt commented on soco/alarms.py
> +            from_datetime = datetime().now()
Replace with `datetime.now()`

2023-11-12 13:59 UTC, pwt commented
I've fixed the check jobs so that all checks on `master` are now passing. If you rebase, you'll pick up the fix.

You'll also need to address the following -- see code review comments.
```
************* Module soco.alarms
soco/alarms.py:205:28: E1120: No value for argument 'year' in constructor call (no-value-for-parameter)
soco/alarms.py:430:28: E1120: No value for argument 'year' in constructor call (no-value-for-parameter)
soco/alarms.py:470:35: E1101: Class 'datetime' has no 'timedelta' member (no-member)
```

2023-11-13 04:37 UTC, DaAwesomeP commented on soco/alarms.py
> +            from_datetime = datetime().now()
Fixed!

2023-11-13 04:37 UTC, DaAwesomeP commented on soco/alarms.py
> +            from_datetime = datetime().now()
Fixed!

2023-11-13 04:37 UTC, DaAwesomeP commented on soco/alarms.py
> +            from_datetime.date() + datetime.timedelta(days=offset),
Fixed!

2023-11-13 04:41 UTC, DaAwesomeP commented
@pwt Thanks for the review! OK, I have fixed your notes (I did not see those errors for Python 3.12 before). I have also now actually tried this out and fixed some other bugs that I did not find before. I added a `zone_uid` filter to make it easier to for the next alarm by device zone.

2023-11-19 10:53 UTC, pwt requested changes
This all looks great to me -- thanks.

I'd remove the `assert` statements (lines 453 and 461/462), unless there's a specific reason you think they should remain for the production release -- then I think we're all set to merge.

2023-11-19 13:56 UTC, DaAwesomeP commented
> I'd remove the `assert` statements (lines 453 and 461/462), unless there's a specific reason you think they should remain for the production release -- then I think we're all set to merge.

Ah, yeah sorry, all fixed! Thank you!

2023-11-28 20:10 UTC, pwt approved these changes

2023-11-28 20:11 UTC, merged